/**
 * RECALLER console — service layer.
 *
 * Every screen talks to the application through this module and nothing else.
 * It currently runs the deterministic domain packages in-process (Phase 1/3),
 * which is what makes the demo installable with no server. Pointing it at the
 * RECALLER backend is a transport change inside this one file: each function
 * below maps one-to-one onto an endpoint in app-backend.
 *
 *   listApplications   → GET    /api/applications
 *   getApplication     → GET    /api/applications/:id
 *   createApplication  → POST   /api/applications
 *   startUnderwriting  → POST   /api/applications/:id/underwrite
 *   resumeUnderwriting → POST   /api/applications/:id/resume
 *   replayApplication  → POST   /api/applications/:id/replay
 *   solveWhatIf        → POST   /api/applications/:id/whatif
 *   simulateScenario   → POST   /api/applications/:id/simulate
 *
 * The UI performs no credit arithmetic and evaluates no policy rule. When a
 * number appears on a screen, it arrived from here already computed.
 */

import policyV1 from '@policy/policy.v1.json';
import { SYNTHETIC_APPLICATIONS } from '@synthetic/applications.js';
import {
  runUnderwriting,
  resumeUnderwriting as resumeRun,
  replay as replayRun,
  runWhatIf,
  runSimulation,
  STAGE_PLAN,
} from '@orchestrator/index.js';
import { APP_STATUS } from '@core/constants.js';

export const POLICY = policyV1;
export { STAGE_PLAN };

/** Transport mode. `local` runs the engine in the browser; `http` calls app-backend. */
export const MODE = import.meta.env.VITE_RECALLER_API ? 'http' : 'local';
const BASE = import.meta.env.VITE_RECALLER_API ?? '';

/* ================================================================== *
 * Store
 * ================================================================== */

const LS_KEY = 'recaller.console.v1';

const state = {
  /** application id → header (borrower, asset, loan request, status) */
  applications: new Map(),
  /** application id → document bundle (with synthetic payloads) */
  bundles: new Map(),
  /** application id → completed or suspended underwriting record */
  records: new Map(),
  /** application id → { [stageId]: 'PENDING' | 'RUNNING' | 'DONE' | 'HELD' } */
  progress: new Map(),
  /** application id → replay results, newest first */
  replays: new Map(),
};

const listeners = new Set();
let snapshotToken = 0;
let snapshot = null;

function emit() {
  snapshotToken += 1;
  snapshot = null;
  listeners.forEach((fn) => fn());
}

export function subscribe(fn) {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

/** Stable snapshot for useSyncExternalStore — identity changes only on emit. */
export function getSnapshot() {
  if (snapshot === null) {
    snapshot = {
      token: snapshotToken,
      applications: [...state.applications.values()],
      records: state.records,
      progress: state.progress,
      replays: state.replays,
    };
  }
  return snapshot;
}

/* ---- seeding & persistence ---------------------------------------- */

/**
 * Persistence stores intent, not output: the application header, which
 * documents were attached, and what the officer decided. Records are
 * regenerated by re-running the pipeline, which is safe precisely because the
 * pipeline is deterministic — a rehydrated record is bit-identical to the one
 * that was stored, and far smaller on disk.
 */
function persist() {
  try {
    const payload = {
      v: 1,
      apps: [...state.applications.values()].map((a) => ({
        id: a.id,
        header: stripRuntime(a),
        processed: state.records.has(a.id),
        resolutions: state.records.get(a.id)?.resolutions ?? [],
        custom: a.custom ?? false,
        documents: a.custom ? state.bundles.get(a.id) : null,
      })),
    };
    localStorage.setItem(LS_KEY, JSON.stringify(payload));
  } catch {
    /* storage unavailable (private window, quota) — the console still works */
  }
}

function stripRuntime(a) {
  const { documents, scenario, ...rest } = a;
  return rest;
}

let seeded = false;

export async function seed() {
  if (seeded) return;
  seeded = true;

  SYNTHETIC_APPLICATIONS.forEach((app) => {
    const { documents, scenario, ...header } = app;
    state.applications.set(app.id, {
      ...header,
      scenario,
      status: APP_STATUS.DRAFT,
      decision: null,
      updated_at: header.created_at,
      custom: false,
      document_count: documents.length,
    });
    state.bundles.set(app.id, documents);
    state.progress.set(app.id, blankProgress());
  });

  // Restore whatever the officer had already done in a previous session.
  let saved = null;
  try {
    saved = JSON.parse(localStorage.getItem(LS_KEY) ?? 'null');
  } catch {
    saved = null;
  }

  if (saved?.apps) {
    for (const entry of saved.apps) {
      if (entry.custom && entry.documents) {
        state.applications.set(entry.id, { ...entry.header, custom: true });
        state.bundles.set(entry.id, entry.documents);
        state.progress.set(entry.id, blankProgress());
      }
      if (entry.processed && state.bundles.has(entry.id)) {
        // eslint-disable-next-line no-await-in-loop
        await rehydrate(entry.id, entry.resolutions ?? []);
      }
    }
  }

  emit();
}

function blankProgress() {
  return Object.fromEntries(STAGE_PLAN.map((s) => [s.id, 'PENDING']));
}

async function rehydrate(id, resolutions) {
  const header = state.applications.get(id);
  const documents = state.bundles.get(id);
  if (!header || !documents) return;
  let record = await runUnderwriting({
    application: toRequest(header),
    documents,
    policy: POLICY,
    now: header.created_at,
  });
  if (record.status === APP_STATUS.WAITING_FOR_OFFICER && resolutions.length) {
    record = await resumeRun({ record, resolutions, policy: POLICY, now: header.created_at });
  }
  commit(id, record);
}

function toRequest(header) {
  const { scenario, status, decision, updated_at, custom, document_count, ...rest } = header;
  return rest;
}

function commit(id, record) {
  state.records.set(id, record);
  const header = state.applications.get(id);
  state.applications.set(id, {
    ...header,
    status: record.status,
    decision: record.decision?.decision ?? null,
    updated_at: record.generated_at ?? new Date().toISOString(),
  });
  const progress = blankProgress();
  const completed = record.checkpoint?.completed_stages ?? STAGE_PLAN.map((s) => s.id);
  completed.forEach((s) => {
    progress[s] = 'DONE';
  });
  if (record.status === APP_STATUS.WAITING_FOR_OFFICER) progress.GATE = 'HELD';
  state.progress.set(id, progress);
}

/* ================================================================== *
 * Read
 * ================================================================== */

export function listApplications() {
  return getSnapshot().applications;
}

export function getApplication(id) {
  return state.applications.get(id) ?? null;
}

export function getDocuments(id) {
  return (state.bundles.get(id) ?? []).map(({ payload, degrade, ...d }) => d);
}

export function getRecord(id) {
  return state.records.get(id) ?? null;
}

export function getProgress(id) {
  return state.progress.get(id) ?? blankProgress();
}

export function getReplays(id) {
  return state.replays.get(id) ?? [];
}

/* ================================================================== *
 * Write
 * ================================================================== */

let sequence = 500;

export function createApplication(form, documents) {
  sequence += 1;
  const id = `RCL-2026-0${sequence}`;
  const header = {
    id,
    borrower_name: form.borrower_name,
    segment: form.segment,
    loan_amount: Number(form.loan_amount),
    tenure_months: Number(form.tenure_months),
    declared_monthly_income: Number(form.declared_monthly_income),
    branch: form.branch,
    officer: form.officer,
    dealer: form.dealer,
    occupation: form.occupation,
    created_at: new Date().toISOString(),
    status: APP_STATUS.DRAFT,
    decision: null,
    updated_at: new Date().toISOString(),
    custom: true,
    document_count: documents.length,
  };
  state.applications.set(id, header);
  state.bundles.set(id, documents);
  state.progress.set(id, blankProgress());
  persist();
  emit();
  return id;
}

/**
 * Stage pacing.
 *
 * The deterministic engine returns in single-digit milliseconds, which would
 * make the processing view a flicker. These delays exist so a human can watch
 * the workflow advance and see which stage is executing — they model the
 * latency of real document understanding, and are replaced by genuine n8n
 * execution timings once the orchestrator is wired in (Phase 4).
 */
const STAGE_PACING = {
  INGEST: 380,
  KYC: 900,
  BANK: 1500,
  PLATFORM: 850,
  INVOICE: 780,
  VALIDATE: 420,
  RECONCILE: 620,
  GATE: 340,
  CREDIT: 520,
  POLICY: 460,
  DECISION: 380,
  MEMO: 700,
};

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

export async function startUnderwriting(id, { paced = true } = {}) {
  const header = state.applications.get(id);
  const documents = state.bundles.get(id);
  if (!header || !documents) throw new Error(`Unknown application ${id}`);

  setStatus(id, APP_STATUS.PROCESSING);
  state.progress.set(id, blankProgress());
  emit();

  const record = await runUnderwriting({
    application: toRequest(header),
    documents,
    policy: POLICY,
    onStage: async ({ id: stageId, status }) => {
      const p = { ...state.progress.get(id), [stageId]: status };
      state.progress.set(id, p);
      emit();
      if (paced && status === 'RUNNING') await sleep(STAGE_PACING[stageId] ?? 400);
    },
  });

  commit(id, record);
  persist();
  emit();
  return record;
}

export async function resumeUnderwriting(id, resolutions, { paced = true } = {}) {
  const record = state.records.get(id);
  if (!record) throw new Error(`No suspended execution for ${id}`);

  setStatus(id, APP_STATUS.PROCESSING);
  emit();

  const next = await resumeRun({
    record,
    resolutions,
    policy: POLICY,
    onStage: async ({ id: stageId, status }) => {
      const p = { ...state.progress.get(id), [stageId]: status };
      state.progress.set(id, p);
      emit();
      if (paced && status === 'RUNNING') await sleep(STAGE_PACING[stageId] ?? 400);
    },
  });

  commit(id, next);
  persist();
  emit();
  return next;
}

export async function replayApplication(id, { policy = POLICY, label } = {}) {
  const record = state.records.get(id);
  if (!record) throw new Error(`Nothing to replay for ${id}`);
  const result = await replayRun({ record, policy, label });
  state.replays.set(id, [result, ...(state.replays.get(id) ?? [])].slice(0, 12));
  emit();
  return result;
}

export function solveWhatIf(id, target) {
  const record = state.records.get(id);
  if (!record?.credit) return null;
  return runWhatIf({ record, policy: POLICY, target });
}

export function simulateScenario(id, scenario) {
  const record = state.records.get(id);
  if (!record?.credit) return null;
  return runSimulation({ record, policy: POLICY, scenario });
}

function setStatus(id, status) {
  const header = state.applications.get(id);
  state.applications.set(id, { ...header, status, updated_at: new Date().toISOString() });
}

/**
 * Build an amended policy for "replay with current policy" — the officer edits
 * a threshold and the same frozen evidence is judged against the new rulebook.
 */
export function amendPolicy(overrides) {
  const rules = POLICY.rules.map((r) =>
    overrides[r.code] === undefined ? r : { ...r, threshold: Number(overrides[r.code]) },
  );
  return { ...POLICY, rules, version: `${POLICY.version}+local`, effective_date: new Date().toISOString().slice(0, 10) };
}

export function resetConsole() {
  try {
    localStorage.removeItem(LS_KEY);
  } catch {
    /* ignore */
  }
  state.records.clear();
  state.replays.clear();
  SYNTHETIC_APPLICATIONS.forEach((app) => {
    const header = state.applications.get(app.id);
    if (header) {
      state.applications.set(app.id, { ...header, status: APP_STATUS.DRAFT, decision: null });
      state.progress.set(app.id, blankProgress());
    }
  });
  emit();
}
