/**
 * Engine transport — the deterministic domain packages, executed in the browser.
 *
 * This is the offline / demo mode. It is not a second implementation and not a
 * parallel mock schema: it calls the same orchestrator, the same credit engine
 * and the same policy document the backend calls, so a record produced here is
 * byte-for-byte the record the backend would have produced.
 *
 * The UI still performs no credit arithmetic — it only ever reads what these
 * functions return.
 */

import { verifyLedger } from '@core/audit.js'
import {
  APP_STATUS,
  DOC_LABELS,
  OPTIONAL_DOCS,
  PROVENANCE,
  REQUIRED_DOCS,
  STATUS_LABELS,
} from '@core/constants.js'
import {
  STAGE_PLAN,
  replay as replayRun,
  resumeUnderwriting as resumeRun,
  runSimulation,
  runUnderwriting,
  runWhatIf,
} from '@orchestrator/index.js'
import { DECISIONS, ENGINE_VERSION, WORKFLOW_VERSION } from '@core/constants.js'
import { STAGE_LABELS } from '@core/audit.js'
import policyV1 from '@policy/policy.v1.json'
import { SYNTHETIC_APPLICATIONS } from '@synthetic/applications.js'

/**
 * Stage pacing.
 *
 * The deterministic engine returns in single-digit milliseconds, which would
 * make the run view a flicker. These delays mirror `STAGE_PACING` in the
 * backend store so both transports feel identical, and they model the latency
 * of real document understanding.
 */
const STAGE_PACING = {
  INGEST: 380,
  KYC: 900,
  BANK: 1500,
  PLATFORM: 850,
  INVOICE: 780,
  VALIDATE: 420,
  RECONCILE: 620,
  GATE: 340,
  CREDIT: 520,
  POLICY: 460,
  DECISION: 380,
  MEMO: 700,
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

const blankProgress = () => Object.fromEntries(STAGE_PLAN.map((s) => [s.id, 'PENDING']))

const stripRuntime = ({ scenario, status, decision, updated_at, custom, document_count, ...rest }) => rest

/**
 * State is anchored on globalThis rather than module scope: Vite's HMR
 * re-imports a changed module under a cache-busting URL, which would otherwise
 * fork the store and leave the mounted tree reading an empty copy.
 */
const KEY = '__recaller_engine_store__'
const LS_KEY = 'recaller.console.v1'

function createState() {
  const state = {
    applications: new Map(),
    bundles: new Map(),
    records: new Map(),
    progress: new Map(),
    replays: new Map(),
    restored: null,
  }
  seed(state)
  return state
}

/**
 * Persistence stores intent, not output: which files were processed and what
 * the officer decided. Records are regenerated by re-running the pipeline,
 * which is safe precisely because the pipeline is deterministic — a rehydrated
 * record is identical to the one that was stored, and far smaller on disk.
 */
function persist(state) {
  try {
    localStorage.setItem(
      LS_KEY,
      JSON.stringify({
        v: 1,
        apps: [...state.records.keys()].map((id) => ({
          id,
          resolutions: state.records.get(id)?.resolutions ?? [],
        })),
      }),
    )
  } catch {
    /* storage unavailable (private window, quota) — the console still works */
  }
}

/**
 * Replay what the officer had already done, once per page load. Each entry is
 * restored independently: one unreadable record must not cost the officer the
 * rest of the queue.
 */
async function restore(state) {
  let saved = null
  try {
    saved = JSON.parse(localStorage.getItem(LS_KEY) ?? 'null')
  } catch {
    saved = null
  }
  if (!saved?.apps?.length) return

  for (const entry of saved.apps) {
    const header = state.applications.get(entry.id)
    const documents = state.bundles.get(entry.id)
    if (!header || !documents) continue
    try {
      // eslint-disable-next-line no-await-in-loop
      let record = await runUnderwriting({
        application: stripRuntime(header),
        documents,
        policy: policyV1,
        now: header.created_at,
      })
      if (record.status === APP_STATUS.WAITING_FOR_OFFICER && entry.resolutions?.length) {
        // eslint-disable-next-line no-await-in-loop
        record = await resumeRun({
          record,
          resolutions: entry.resolutions,
          policy: policyV1,
          now: header.created_at,
        })
      }
      commit(state, entry.id, record)
    } catch (err) {
      console.error(`[recaller] could not restore ${entry.id}; it returns to its unprocessed state.`, err)
    }
  }
}

const ensureRestored = (state) => (state.restored ??= restore(state))

function seed(state) {
  SYNTHETIC_APPLICATIONS.forEach((app) => {
    const { documents, scenario, ...header } = app
    state.applications.set(app.id, {
      ...header,
      scenario,
      status: APP_STATUS.DRAFT,
      decision: null,
      updated_at: header.created_at,
      custom: false,
      document_count: documents.length,
    })
    state.bundles.set(app.id, documents)
    state.progress.set(app.id, blankProgress())
  })
}

function commit(state, id, record) {
  state.records.set(id, record)
  const header = state.applications.get(id)
  state.applications.set(id, {
    ...header,
    status: record.status,
    decision: record.decision?.decision ?? null,
    updated_at: record.generated_at ?? new Date().toISOString(),
  })

  const progress = blankProgress()
  const completed = record.checkpoint?.completed_stages ?? STAGE_PLAN.map((s) => s.id)
  completed.forEach((s) => {
    progress[s] = 'DONE'
  })
  if (record.status === APP_STATUS.WAITING_FOR_OFFICER) progress.GATE = 'HELD'
  state.progress.set(id, progress)
}

export function createEngineTransport() {
  const state = globalThis[KEY] ?? (globalThis[KEY] = createState())

  const stageListener = (id, onStage, paced) => async ({ id: stageId, status }) => {
    state.progress.set(id, { ...state.progress.get(id), [stageId]: status })
    onStage?.({ id: stageId, status })
    if (paced && status === 'RUNNING') await sleep(STAGE_PACING[stageId] ?? 400)
  }

  const requireRecord = (id) => {
    const record = state.records.get(id)
    if (!record) throw new Error(`No underwriting record for ${id}`)
    return record
  }

  return {
    name: 'engine',

    async health() {
      return {
        status: 'ok',
        engine_version: ENGINE_VERSION,
        workflow_version: WORKFLOW_VERSION,
      }
    },

    async getPolicy() {
      return policyV1
    },

    async getStagePlan() {
      return STAGE_PLAN
    },

    /** Mirrors GET /api/bootstrap: everything the console needs to start. */
    async bootstrap() {
      await ensureRestored(state)
      return {
        engine_version: ENGINE_VERSION,
        workflow_version: WORKFLOW_VERSION,
        policy: policyV1,
        stage_plan: STAGE_PLAN,
        applications: [...state.applications.values()],
        vocab: {
          status_labels: STATUS_LABELS,
          doc_labels: DOC_LABELS,
          required_docs: REQUIRED_DOCS,
          optional_docs: OPTIONAL_DOCS,
          provenance: PROVENANCE,
          decisions: DECISIONS.ALL ?? [DECISIONS.APPROVE, DECISIONS.REFER, DECISIONS.REJECT],
          stage_labels: STAGE_LABELS,
        },
        llm: { enabled: false, provider: null, model: null },
      }
    },

    /** Mirrors GET /api/applications/:id/audit/verify. */
    async verifyAudit(id) {
      const record = requireRecord(id)
      const ledger = record.audit ?? { events: [] }
      return {
        ...verifyLedger(ledger),
        events: ledger.events?.length ?? 0,
        head: ledger.head,
        trace_id: ledger.traceId,
      }
    },

    async listApplications() {
      return [...state.applications.values()]
    },

    async getApplication(id) {
      const application = state.applications.get(id)
      if (!application) throw new Error(`Application ${id} not found`)
      const record = state.records.get(id) ?? null
      return {
        application,
        documents: (state.bundles.get(id) ?? []).map(({ payload, degrade, ...d }) => d),
        // the backend stamps the ledger verification onto the record it serves
        record: record && { ...record, audit_verification: verifyLedger(record.audit ?? { events: [] }) },
        progress: state.progress.get(id) ?? blankProgress(),
        replays: state.replays.get(id) ?? [],
      }
    },

    async createApplication(form) {
      const year = new Date().getFullYear()
      const seq = 500 + state.applications.size + 1
      const id = `RCL-${year}-${String(seq).padStart(4, '0')}`
      const ts = new Date().toISOString()
      const app = {
        id,
        borrower_name: (form.borrower_name || 'New Applicant').trim(),
        segment: form.segment || 'EV_2W',
        loan_amount: Number(form.loan_amount) || 95000,
        tenure_months: Number(form.tenure_months) || 36,
        declared_monthly_income: Number(form.declared_monthly_income) || 32000,
        branch: form.branch || 'Delhi — Karol Bagh',
        officer: form.officer || 'Console Officer',
        dealer: form.dealer || 'Volt Mobility, Karol Bagh',
        occupation: form.occupation || 'Gig worker',
        created_at: ts,
        updated_at: ts,
        status: APP_STATUS.DRAFT,
        decision: null,
        custom: true,
        document_count: 0,
      }
      state.applications.set(id, app)
      state.bundles.set(id, [])
      persist(state)
      return app
    },

    async uploadDocument(id, type, file) {
      const app = state.applications.get(id)
      if (!app) throw new Error(`Application ${id} not found`)
      const docs = state.bundles.get(id) ?? []
      const docId = `${id}-${type}-${Math.random().toString(36).slice(2, 7)}`
      const newDoc = {
        id: docId,
        app_id: id,
        type,
        filename: file?.name || `${type.toLowerCase()}.pdf`,
        source: 'upload',
        media_type: file?.type || 'application/pdf',
        pages: 1,
        size_kb: Math.round(((file?.size || 1024) / 1024) * 10) / 10,
        uploaded_at: new Date().toISOString(),
      }
      state.bundles.set(id, [...docs.filter((d) => d.type !== type), newDoc])
      app.document_count = (state.bundles.get(id) ?? []).length
      state.applications.set(id, { ...app })
      persist(state)
      return newDoc
    },

    async extractApplicationDraft(file) {
      let text = ''
      try {
        if (file && typeof file.text === 'function') {
          text = await file.text()
        }
      } catch {
        text = ''
      }
      const fn = file?.name || 'document.pdf'
      const is3w = /cargo|loader|passenger|rickshaw|auto/i.test(fn + text)
      const isCargo = /cargo|loader/i.test(fn + text)
      return {
        success: true,
        filename: fn,
        media_type: file?.type || 'application/pdf',
        page_count: 1,
        ocr_used: false,
        scanned: false,
        text_preview: text.slice(0, 300) || `Scanned document: ${fn}`,
        extracted_fields: {
          borrower_name: fn.replace(/\.[^/.]+$/, '').replace(/[_-]/g, ' ') || 'New Applicant',
          segment: isCargo ? 'EV_3W_CARGO' : is3w ? 'EV_3W_PASSENGER' : 'EV_2W',
          loan_amount: is3w ? 220000 : 95000,
          tenure_months: 36,
          declared_monthly_income: is3w ? 42000 : 32000,
          branch: 'Delhi — Karol Bagh',
          dealer: 'Volt Mobility, Karol Bagh',
          occupation: isCargo ? 'Last-mile delivery' : is3w ? 'E-rickshaw operator' : 'Ride-hailing driver',
          detected_doc_type: /pan/i.test(fn) ? 'PAN' : /aadhaar/i.test(fn) ? 'AADHAAR' : 'DEALER_INVOICE',
          confidence: 0.9,
          snippet: `Extracted from ${fn}`,
        },
      }
    },

    async startUnderwriting(id, { paced = true, onStage } = {}) {
      const header = state.applications.get(id)
      const documents = state.bundles.get(id)
      if (!header || !documents) throw new Error(`Unknown application ${id}`)

      state.applications.set(id, { ...header, status: APP_STATUS.PROCESSING })
      state.progress.set(id, blankProgress())

      const record = await runUnderwriting({
        application: stripRuntime(header),
        documents,
        policy: policyV1,
        onStage: stageListener(id, onStage, paced),
      })

      commit(state, id, record)
      persist(state)
      return record
    },

    async resumeUnderwriting(id, resolutions, { paced = true, onStage } = {}) {
      const record = requireRecord(id)
      state.applications.set(id, { ...state.applications.get(id), status: APP_STATUS.PROCESSING })

      const next = await resumeRun({
        record,
        resolutions,
        policy: policyV1,
        onStage: stageListener(id, onStage, paced),
      })

      commit(state, id, next)
      persist(state)
      return next
    },

    async replayApplication(id, { policy = null, label } = {}) {
      const record = requireRecord(id)
      const result = await replayRun({ record, policy: policy ?? policyV1, label })
      state.replays.set(id, [result, ...(state.replays.get(id) ?? [])].slice(0, 12))
      return result
    },

    async solveWhatIf(id, target = 'APPROVE') {
      const record = requireRecord(id)
      if (!record.credit) throw new Error(`Cannot run what-if on ${id}`)
      return runWhatIf({ record, policy: policyV1, target })
    },

    async simulateScenario(id, scenario) {
      const record = requireRecord(id)
      if (!record.credit) throw new Error(`Cannot simulate on ${id}`)
      return runSimulation({ record, policy: policyV1, scenario })
    },

    async resetConsole() {
      try {
        localStorage.removeItem(LS_KEY)
      } catch {
        /* ignore */
      }
      state.restored = Promise.resolve()
      state.records.clear()
      state.replays.clear()
      state.applications.clear()
      state.bundles.clear()
      state.progress.clear()
      seed(state)
      return { ok: true, applications: [...state.applications.values()] }
    },
  }
}
