import { motion } from 'framer-motion'
import { Button } from '../components/ui'
import './premium.css'

const evidence = [['KYC', 'IDENTITY', '99.2% confidence'], ['BANK', 'CASH FLOW', '₹28,740 avg.'], ['UPI', 'SETTLEMENTS', 'Verified'], ['INVOICE', 'ASSET VALUE', '₹1,20,000'], ['PLATFORM', 'EARNINGS', '₹29,100 avg.']]
const steps = ['INGEST', 'EXTRACT', 'RECONCILE', 'POLICY', 'DECISION', 'NARRATE', 'AUDIT']

function Reveal({ children, className = '' }) { return <motion.div className={className} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .16 }} transition={{ duration: .7, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div> }
function Eyebrow({ children }) { return <p className="story__eyebrow">{children}</p> }
function FakeConsole({ decision = 'APPROVE' }) { return <div className="fake-console"><div className="fake-console__top"><span>RECALLER / UNDERWRITING</span><span>POLICY / V1.0.0</span></div><div className="fake-console__body"><aside><b>APPLICATIONS</b><span className="is-active">Underwriting</span><span>Evidence</span><span>Reconciliation</span><span>What-if</span><span>Assist</span><span>Audit</span></aside><main><div className="fake-console__app"><p>APPLICATION / APP-2001</p><h3>Meera Raghavan</h3><small>EV TWO-WHEELER · ₹85,000</small></div><div className={`fake-console__decision ${decision.toLowerCase()}`}><small>DECISION</small><strong>{decision}</strong><div><span>FOIR <b>16.5%</b></span><span>EMI <b>₹3,442</b></span><span>LTV <b>70%</b></span></div></div></main></div></div> }

export default function PremiumStories() {
  return <>
    <section id="product" className="story story--dark story--problem"><div className="wrap"><Reveal><Eyebrow>01 / THE SIGNALS</Eyebrow><h2>THE SALARY SLIP<br />DISAPPEARS.<br /><span>THE EVIDENCE DOESN'T.</span></h2><p className="story__lede">RECALLER works with the financial signals thin-file borrowers actually produce.</p></Reveal><div className="evidence-float">{evidence.map(([type, label, value], i) => <Reveal className={`evidence-float__card card-${i}`} key={type}><small>{type}</small><b>{label}</b><span>{value}</span></Reveal>)}</div></div></section>

    <section id="how" className="story story--light"><div className="wrap"><Reveal><Eyebrow>02 / RECONCILIATION</Eyebrow><h2>EVERYTHING<br />YOU CAN VERIFY.</h2><p className="story__lede">Cross-document reconciliation catches the contradictions traditional underwriting misses.</p></Reveal><Reveal className="recon-mock"><header><span>RECALLER / RECONCILIATION</span><span>4 DOCUMENTS</span></header><div className="recon-mock__docs"><span>KYC</span><span>BANK STATEMENT</span><span>UPI SETTLEMENT</span><span>DEALER INVOICE</span></div><div className="recon-mock__row"><small>NAME / BLOCKING</small><b>Rakesh Kumar Yadav <i>vs</i> Ramesh Kumar Yadav</b><em>HUMAN REVIEW</em></div><div className="recon-mock__row"><small>DECLARED INCOME / MATERIAL MISMATCH</small><b>₹52,000 <i>vs</i> ₹23,817 OBSERVED</b><em>ENGINE USES VERIFIED FIGURE</em></div></Reveal></div></section>

    <section className="story story--dark story--map"><div className="wrap"><Reveal><Eyebrow>03 / EVIDENCE GRAPH</Eyebrow><h2>FOUR DOCUMENTS.<br />ONE VERSION<br />OF THE TRUTH.</h2></Reveal><Reveal className="truth-map"><span>KYC</span><span>BANK</span><b>RECONCILIATION</b><span>UPI</span><span>INVOICE</span></Reveal></div></section>

    <section className="story story--dark story--product"><div className="wrap"><Reveal className="product-heading"><Eyebrow>04 / PRODUCT CONSOLE</Eyebrow><h2>ONE ACCOUNTABLE<br />DECISION.</h2><p className="story__lede">A real underwriting workflow — evidence, computation, policy and audit — connected to one file.</p></Reveal><Reveal><FakeConsole /></Reveal><div className="product-notes"><span>DETERMINISTIC<br />COMPUTATION</span><span>EVIDENCE<br />RECONCILIATION</span><span>REPLAYABLE<br />DECISION</span></div></div></section>

    <section className="story story--light story--compute"><div className="wrap"><Reveal><Eyebrow>05 / COMPUTATION</Eyebrow><h2>THE MODEL NEVER<br />CALCULATES THE MONEY.</h2><p className="story__lede">FOIR, EMI and LTV come from deterministic policy code. AI only narrates the resulting decision.</p></Reveal><div className="compute-grid">{[['FOIR', 'Income / ₹30,000', 'Obligations / ₹9,000', '30%'], ['EMI', 'Principal / ₹85,000', 'Term / 36 months', '₹3,442'], ['LTV', 'Asset / ₹1,20,000', 'Eligible / ₹85,000', '70%']].map(([n,a,b,r]) => <Reveal className="compute-card" key={n}><small>{n} / COMPUTED</small><p>{a}</p><p>{b}</p><strong>{r}</strong></Reveal>)}</div></div></section>

    <section className="story story--dark story--policy"><div className="wrap split-story"><Reveal><Eyebrow>06 / POLICY AS CONFIG</Eyebrow><h2>CHANGE THE POLICY.<br />NOT THE CODE.</h2><p className="story__lede">Rules are visible, versioned and rerunnable. No silent financial math in the interface.</p></Reveal><Reveal className="policy-card"><small>RECALLER-GREEN-RETAIL / V1.0.0</small><dl><div><dt>FOIR CAP</dt><dd>50%</dd></div><div><dt>LTV CAP</dt><dd>85%</dd></div><div><dt>MAX TICKET</dt><dd>₹2,00,000</dd></div></dl><footer><span>ELIGIBLE AMOUNT</span><b>₹77,000</b></footer></Reveal></div></section>

    <section className="story story--light story--whatif"><div className="wrap"><Reveal><Eyebrow>07 / WHAT-IF</Eyebrow><h2>WHAT IF THE<br />DECISION COULD MOVE?</h2></Reveal><Reveal className="whatif-mock"><div><small>BASELINE</small><b className="is-reject">DECLINE</b><span>FOIR 56%</span></div><div className="whatif-mock__control"><small>TENURE</small><b>24 <i /> 36 MONTHS</b><input aria-label="Illustrative tenure control" type="range" min="24" max="36" value="36" readOnly /></div><div><small>RECOMPUTED</small><b className="is-approve">APPROVE</b><span>FOIR 46%</span></div></Reveal></div></section>

    <section id="trust" className="story story--dark"><div className="wrap"><Reveal><Eyebrow>08 / TRUST</Eyebrow><h2>EVERY DECISION<br />LEAVES A TRACE.</h2></Reveal><Reveal className="audit-line">{steps.map((step, i) => <div key={step}><i>{String(i + 1).padStart(2, '0')}</i><b>{step}</b><span>{i === 6 ? 'FINGERPRINTED' : 'COMPLETE'}</span></div>)}</Reveal><div className="trust-claims"><Reveal><b>DETERMINISTIC</b><span>Numbers come from code.</span></Reveal><Reveal><b>EVIDENCE-BACKED</b><span>Every decision references a source.</span></Reveal><Reveal><b>REPLAYABLE</b><span>Every decision can be reconstructed.</span></Reveal></div></div></section>

    <section id="download" className="story story--final"><div className="wrap"><Reveal><Eyebrow>RECALLER / LOCAL PRODUCT DEMO</Eyebrow><h2>SEE THE DECISION.<br />NOT JUST THE SCORE.</h2><p className="story__lede">Run the complete RECALLER underwriting workflow locally.</p><Button to="/console" size="lg">Open console</Button></Reveal><div className="system-metrics"><span><b>4</b>SYNTHETIC CASES</span><span><b>1</b>REPLAYABLE PATH</span><span><b>∞</b>EVIDENCE CITATIONS</span></div><p className="final-mark">RECALLER<span>.</span></p></div></section>
  </>
}
